language: node_js
node_js:
  - 16

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version # Print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag reverseproxy:v1a buithang23/reverseproxy:v1a
  - docker push buithang23/reverseproxy:v1a
  - docker tag udagram-api-user:v1a buithang23/udagram-api-user:v1a
  - docker push buithang23/udagram-api-user:v1a
  - docker tag udagram-api-feed:v1a buithang23/udagram-api-feed:v1a
  - docker push buithang23/udagram-api-feed:v1a
  - docker tag udagram-frontend:local buithang23/udagram-frontend:local
  - docker push buithang23/udagram-frontend:local
