language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

script:
  - docker --version # print the version for logging
  # Build
  - docker-compose -f docker-compose-build.yaml build
  # Tagging
  - docker tag udagram-api-feed:v1a buithang23/udagram-api-feed:v1a
  - docker tag udagram-api-user:v1a buithang23/udagram-api-user:v1a
  - docker tag udagram-frontend:local buithang23/udagram-frontend:local
  - docker tag reverseproxy:v1a buithang23/reverseproxy:v1a

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push buithang23/reverseproxy:v1a
  - docker push buithang23/udagram-api-user:v1a
  - docker push buithang23/udagram-api-feed:v1a
  - docker push buithang23/udagram-frontend:local
