apiVersion: apps/v1
kind: HorizontalPodAutoscaler
metadata:
 name: api-feed
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: api-feed
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 70